MODEL:
  WEIGHT: "./weights/kitti/DLA/2/model_final.pth"
INPUT:
  FLIP_PROB_TRAIN: 0.5
  SHIFT_SCALE_PROB_TRAIN: 0.3
DATASETS:
  DETECT_CLASSES: ("Car", "Cyclist", "Pedestrian")
  TRAIN: ("kitti_train",)
  TEST: ("kitti_test",)
  TRAIN_SPLIT: "trainval"
  TEST_SPLIT: "test"
SOLVER:
  BASE_LR: 2.0e-4
  STEPS: (10, 20, 30, 40)
  MAX_EPOCH: 50
  IMS_PER_BATCH: 8
  FINETUNE: True
  RESUME: False
